const assert = require("node:assert/strict");
const { chromium } = require("playwright-core");
const { CHROME, BASE, SHOTS } = require("./env");
(async () => {
  const browser = await chromium.launch({ executablePath: CHROME });
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 }, serviceWorkers: "block" });
    await page.route("**/*", (r) => r.request().url().startsWith(BASE) ? r.continue() : r.abort());
    await page.addInitScript(() => localStorage.setItem("bittracker-cloud-sync-config-v1", JSON.stringify({ enabled: false })));
    page.on("dialog", (d) => d.accept());
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(`${BASE}/index.html?micro=flexiones`);
    await page.locator("#denseTrainingForm").waitFor();
    assert.equal(await page.locator("[name='exerciseId']").inputValue(), "floor_push_up");
    assert.equal(await page.evaluate(() => state.denseTrainingEntries.length), 0);
    assert.ok(!page.url().includes("micro="));
    const result = await page.evaluate(async () => {
      closeModal();
      state.settings.microBreaks = { durations: [2, 5], times: ["11:00"], timeZone: "Europe/Madrid", equipment: ["suelo", "anillas", "barra"], kinds: ["activacion", "movilidad"] };
      const date = dateKey(addDays(selectedDate, -3));
      state.denseTrainingEntries = [computeDenseEntry({ id: "push-base", exercise_id: "floor_push_up", nature: "bodyweight", scheme: "5D", date, created_at: `${date}T12:00:00Z`, total_reps: 40, target_reps_per_min: 8, target_total_reps: 40, effort: "N", bodyweight_kg: 80 })];
      state.denseEstimates = {};
      rebuildDenseEstimates(); rebuildTransferState();
      await openMicroProposedSet("flexiones");
      const form = document.querySelector("#denseTrainingForm");
      const target = Number(form.elements.repsPerSet.value);
      const beforeSave = state.denseTrainingEntries.length;
      form.elements.totalReps.value = "30";
      saveDenseTrainingForm(form);
      const saved = state.denseTrainingEntries.find((entry) => entry.id !== "push-base");
      closeModal();
      await openMicroProposedSet("flexiones");
      const blocked = !document.querySelector("#denseTrainingForm") || !nodes.modal.open;
      state.denseTrainingEntries = [computeDenseEntry({ id: "lever-base", exercise_id: "front_lever_adv_tuck", nature: "skill", scheme: "5D", date, created_at: `${date}T13:00:00Z`, total_hold_seconds: 60, hold_seconds_per_round: 12, effort: "N" })];
      state.denseEstimates = {}; rebuildDenseEstimates(); rebuildTransferState();
      await openMicroProposedSet("front-lever");
      const variant = document.querySelector("[name='exerciseId']").value;
      const hold = Number(document.querySelector("[name='holdSecondsPerRound']").value);
      closeModal();
      state.settings.microBreaks.equipment = ["suelo"];
      await openMicroProposedSet("toes-to-bar");
      const noEquipment = !nodes.modal.open;
      state.settings.microBreaks.equipment = ["suelo", "anillas", "barra"];
      return { target, beforeSave, saved: { source: saved.source, total: saved.total_reps, failed: saved.failed }, blocked, variant, hold, noEquipment };
    });
    assert.equal(result.target, 8);
    assert.equal(result.beforeSave, 1);
    assert.deepEqual(result.saved, { source: "notification", total: 30, failed: true });
    assert.ok(result.blocked && result.noEquipment);
    assert.equal(result.variant, "front_lever_adv_tuck");
    assert.equal(result.hold, 12);
    await page.evaluate(() => navigator.serviceWorker.dispatchEvent(new MessageEvent("message", { data: { type: "open-micro-session", id: "handstand" } })));
    await page.locator("#denseTrainingForm").waitFor({ state: "visible" });
    assert.equal(await page.locator("[name='exerciseId']").inputValue(), "straight_handstand");
    await page.waitForTimeout(350);
    await page.screenshot({ path: `${SHOTS}/proposed-set-390.png` });
    assert.ok(await page.evaluate(() => nodes.modalBody.scrollWidth <= nodes.modalBody.clientWidth));
    assert.deepEqual(errors, []);
    console.log("PROPOSED SETS: enlace, push en caliente, objetivos propios, guardado, fatiga y material OK");
  } finally { await browser.close(); }
})().catch((e) => { console.error(e); process.exitCode = 1; });
