const assert = require("node:assert/strict");
const { chromium } = require("playwright-core");
const { CHROME, BASE, SHOTS } = require("./env");
let checks = 0;
const check = (value, message) => { assert.ok(value, message); checks += 1; };

(async () => {
  const browser = await chromium.launch({ executablePath: CHROME });
  try {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block" });
    await context.route("**/*", (route) => route.request().url().startsWith(BASE) || (process.env.QA_ICONS === "1" && route.request().url() === "https://unpkg.com/lucide@1.23.0/dist/umd/lucide.min.js") ? route.continue() : route.abort());
    await context.addInitScript(() => localStorage.setItem("bittracker-cloud-sync-config-v1", JSON.stringify({ enabled: false })));
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    page.on("dialog", (dialog) => dialog.accept());
    await page.clock.install({ time: new Date("2026-09-12T10:00:00Z") });
    await page.clock.pauseAt(new Date("2026-09-12T10:00:01Z"));
    await page.goto(`${BASE}/index.html?noprompt=1`);
    const prepare = () => page.evaluate(() => {
      startExerciseTimer("straight_handstand", { exercise_id: "straight_handstand", nature: "skill", scheme: "5D", prescription: { holdSecondsPerRound: 22 } });
      window.timerCues = [];
      playQuickTimerCue = (kind) => window.timerCues.push(kind);
    });
    const timer = () => page.evaluate(() => ({ results: quickTimerState.roundResults, remaining: quickTimerState.remainingSeconds, running: quickTimerState.running, sessionId: quickTimerState.sessionId, cues: window.timerCues }));
    const action = (name) => page.locator(`[data-action='${name}']`);
    await prepare();
    await action("quick-timer-start").click();
    check((await timer()).running, "El crono arranca");
    await page.clock.fastForward(4000);
    check(!(await timer()).results.some(Boolean), "La preparacion no registra aguantes");
    await page.clock.fastForward(1000);
    check((await timer()).cues.includes("start"), "Aviso al comenzar el primer aguante");
    await page.clock.fastForward(17000);
    check(await action("quick-timer-fall").evaluate((button) => { const rect = button.getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight; }), "Boton de caida visible sin deslizar durante el aguante");
    await page.screenshot({ path: `${SHOTS}/timer-running-390.png` });
    await action("quick-timer-fall").click();
    let value = await timer();
    check(value.results[0].seconds === 17 && value.remaining === 283, "Caer a 4:43 registra 17 s");
    check(await action("quick-timer-fall").isDisabled(), "Una pulsacion no duplica la ronda");
    await page.clock.fastForward(43000);
    value = await timer();
    check(value.remaining === 240 && value.results[0].seconds === 17, "El siguiente set empieza en su minuto y conserva la caida");
    await action("quick-timer-metronome").click();
    await page.clock.fastForward(22000);
    value = await timer();
    check(value.results[1].seconds === 22, "Sin pulsacion se completa el objetivo de 22 s");
    check(value.cues.includes("hold-end"), "El metronomo no silencia el fin del aguante");
    await page.clock.fastForward(218000);
    value = await timer();
    check(value.results.length === 5 && value.results.reduce((sum, round) => sum + round.seconds, 0) === 105, "Cinco rondas reales suman 105 s");
    check(!value.running && value.remaining === 0, "Se detiene al final");
    check((await page.locator(".quick-timer-display strong").innerText()) === "0:00", "El final no vuelve a mostrar 5:00");
    for (const width of [320, 390, 1280]) {
      await page.setViewportSize({ width, height: 844 });
      check(await page.locator("#appModal .modal-body").evaluate((body) => body.scrollWidth <= body.clientWidth + 1), `Crono sin desborde a ${width}px`);
      await page.screenshot({ path: `${SHOTS}/timer-${width}.png` });
    }
    await action("apply-timer-hold").click();
    check(await page.locator("[data-hold-round]").count() === 5, "Registro con desglose por ronda");
    check(await page.locator("[data-hold-round='0']").inputValue() === "17", "El registro recibe los segundos de la caida");
    await page.locator('#denseTrainingForm label').filter({ has: page.locator('[name="readiness"][value="low"]') }).click();
    check(await page.locator('#denseTrainingForm [name="holdSecondsPerRound"]').inputValue() === "22", "Readiness no cambia el objetivo cronometrado");
    await page.locator('#denseTrainingForm [type="submit"]').click();
    await page.clock.runFor(1);
    let saved = await page.evaluate(() => JSON.parse(localStorage.getItem("habbit-tracker-v2")));
    const entryId = saved.denseTrainingEntries[0].id;
    check(saved.denseTrainingEntries[0].total_hold_seconds === 105 && saved.denseTrainingEntries[0].target_total_hold_seconds === 110, "El motor recibe TUT real y objetivo separados");
    check(saved.denseTrainingEntries[0].failed === true, "La caida no cuenta como objetivo cumplido");
    await page.reload();
    await page.evaluate(() => openQuickTimerModal());
    check((await timer()).remaining === 0 && !(await timer()).running, "Recargar conserva el bloque terminado y no reinicia");
    await action("apply-timer-hold").click();
    await page.locator('#denseTrainingForm [name="notes"]').fill("Edicion posterior QA");
    await page.locator('#denseTrainingForm [type="submit"]').click();
    saved = await page.evaluate(() => JSON.parse(localStorage.getItem("habbit-tracker-v2")));
    check(saved.denseTrainingEntries.length === 1 && saved.denseTrainingEntries[0].id === entryId, "Volver a guardar edita la misma marca");
    check(saved.denseTrainingEntries[0].hold_rounds.join(",") === "17,22,22,22,22", "Editar conserva el desglose real");
    await prepare();
    await page.evaluate(() => { quickTimerState.preparationSeconds = 0; });
    await action("quick-timer-start").click();
    await action("quick-timer-fall").click();
    check((await timer()).results[0].seconds === 0, "Caida inmediata guarda cero segundos");
    await action("quick-timer-pause").click();
    await page.clock.fastForward(60000);
    check((await timer()).results.filter(Boolean).length === 1, "Pausar no inventa rondas cumplidas");
    await action("apply-timer-hold").click();
    await page.locator('#denseTrainingForm [type="submit"]').click();
    await page.clock.runFor(1);
    saved = await page.evaluate(() => JSON.parse(localStorage.getItem("habbit-tracker-v2")));
    check(saved.denseTrainingEntries[1].total_hold_seconds === 0, "Cero real no se sustituye por el objetivo");
    check(saved.denseTrainingEntries[1].hold_rounds.every((seconds) => seconds === 0), "Rondas no realizadas permanecen a cero en el registro parcial");
    check(saved.denseTrainingEntries[1].isometric_capacity === 0, "Un cero real no aumenta capacidad");
    await page.evaluate(() => {
      openDenseTrainingModal({ exerciseId: "straight_handstand", planItem: { exercise_id: "straight_handstand", scheme: "5D", nature: "skill", prescription: { holdSecondsPerRound: 22 } } });
    });
    await page.locator('.hold-round-details summary').click();
    await page.locator('[data-hold-round="0"]').fill("17");
    await page.locator('[name="rounds"]').fill("7");
    await page.locator('[name="rounds"]').blur();
    check(await page.locator('[data-hold-round]').count() === 7 && await page.locator('[data-hold-round="6"]').inputValue() === "0", "Rondas anadidas a un desglose real no se inventan completas");
    await page.locator('[name="rounds"]').fill("3");
    await page.locator('[name="rounds"]').blur();
    check(await page.locator('[data-hold-round]').count() === 3 && await page.locator('[data-hold-round="0"]').inputValue() === "17", "Reducir rondas tras confirmar conserva las restantes");
    await page.locator('.modal-head [data-action="close-modal"]').click();
    const signal = await page.evaluate(async () => {
      state.settings.timerVolume = .85;
      const offline = new OfflineAudioContext(1, 48000, 48000);
      quickTimerState.audioContext = offline;
      playTimerBeep(1320, 0, .2);
      playTimerBeep(1320, .3, .2);
      playTimerBeep(1580, .6, .28);
      const samples = (await offline.startRendering()).getChannelData(0);
      let peak = 0, nonzero = 0;
      for (const value of samples) { peak = Math.max(peak, Math.abs(value)); if (Math.abs(value) > .01) nonzero += 1; }
      return { peak, audibleMs: nonzero / 48 };
    });
    check(signal.peak > .4 && signal.peak < 1, "Aviso con mas amplitud que el antiguo, sin clipping");
    check(signal.audibleMs > 500, "Aviso prolongado de tres pulsos");
    check(errors.length === 0, `Sin errores JS: ${errors.join(", ")}`);
    console.log(`TIMER: ${checks} checks OK`);
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
